// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDny9FH2N3TC09eicftsqHDvE3Rhi_NmW0',
    appId: '1:574259675806:web:1c31bf6fd13678c310718f',
    messagingSenderId: '574259675806',
    projectId: 'shared-expenses-41329',
    authDomain: 'shared-expenses-41329.firebaseapp.com',
    storageBucket: 'shared-expenses-41329.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxiVJRRTDQctngqSXdpjkUs3mjWCqQmM8',
    appId: '1:574259675806:android:8a05c0cdb71b9b5f10718f',
    messagingSenderId: '574259675806',
    projectId: 'shared-expenses-41329',
    storageBucket: 'shared-expenses-41329.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANOD9F0PlZbfWMlq2JXl9Dc5Wc2YAu8hk',
    appId: '1:574259675806:ios:28858ce12f5cb8cd10718f',
    messagingSenderId: '574259675806',
    projectId: 'shared-expenses-41329',
    storageBucket: 'shared-expenses-41329.firebasestorage.app',
    iosBundleId: 'com.example.sharedExpenses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANOD9F0PlZbfWMlq2JXl9Dc5Wc2YAu8hk',
    appId: '1:574259675806:ios:28858ce12f5cb8cd10718f',
    messagingSenderId: '574259675806',
    projectId: 'shared-expenses-41329',
    storageBucket: 'shared-expenses-41329.firebasestorage.app',
    iosBundleId: 'com.example.sharedExpenses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDny9FH2N3TC09eicftsqHDvE3Rhi_NmW0',
    appId: '1:574259675806:web:fd5412a558b2897010718f',
    messagingSenderId: '574259675806',
    projectId: 'shared-expenses-41329',
    authDomain: 'shared-expenses-41329.firebaseapp.com',
    storageBucket: 'shared-expenses-41329.firebasestorage.app',
  );
}
